. scripts/common.sh
MVP_ENABLE_TESTS=ON
MVP_ENABLE_DEMO=ON
MVP_ENABLE_PYTHON_WRAPPER=ON
PYTHON_EXE=`which python3`
cd $BUILD_DIR 
cmake $WORK_DIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$BUILD_DIR \
      -DPYTHON_EXECUTABLE=${PYTHON_EXE} \
      -DMVP_ENABLE_TESTS=${MVP_ENABLE_TESTS} \
      -DMVP_ENABLE_DEMO=${MVP_ENABLE_DEMO} \
      -DMVP_ENABLE_PYTHON_WRAPPER=${MVP_ENABLE_PYTHON_WRAPPER}
make -j
