#ifndef MVP_PUBLIC_F3_MVP_FPGA_REG_H
#define MVP_PUBLIC_F3_MVP_FPGA_REG_H

#define MVP_REG_OFFSET 0x0

#define MVP_PROCESS_START_OFFSET 0x0
#define MVP_COMMAND_OFFSET 0x34
#define MVP_LEVEL_OFFSET 0x38
#define MVP_COL_SIZE_OFFSET 0x3C
#define MVP_N_SPLIT_OFFSET 0x40
#define MVP_N_INDEX_OFFSET 0x44
#define MVP_H_MAT_LEN_OFFSET 0x48
#define MVP_KSK_DEV_MEM_LOW_OFFSET 0x4C
#define MVP_KSK_DEV_MEM_HIGH_OFFSET 0x50
#define MVP_H_MAT_DATA_MEM_LOW_OFFSET 0x54
#define MVP_H_MAT_DATA_MEM_HIGH_OFFSET 0x58
#define MVP_H_VEC_DATA_MEM_LOW_OFFSET 0x5C
#define MVP_H_VEC_DATA_MEM_HIGH_OFFSET 0x60
#define MVP_OUTPUT_DATA_MEM_LOW_OFFSET 0x64
#define MVP_OUTPUT_DATA_MEM_HIGH_OFFSET 0x68
#define MVP_OUTPUT_DATA_READY_OFFSET 0x6C

#define FPGA_XDMA_DDR1_READ_DEV_NAME "/dev/xdma0_c2h_1"
#define FPGA_XDMA_DDR1_WRITE_DEV_NAME "/dev/xdma0_h2c_1"

#define RW_MAX_SIZE	0x7ffff000

#define KSK_DEV_BASE_ADDR 0x0000000
#define FIRST_INPUT_DATA_DEV_BASE_ADDR 0x10000000
#define FIRST_OUTPUT_DATA_DEV_BASE_ADDR 0x30000000
#define SECOND_INPUT_DATA_DEV_BASE_ADDR 0x50000000
#define SECOND_OUTPUT_DATA_DEV_BASE_ADDR 0x70000000

#endif  // MVP_PUBLIC_F3_MVP_FPGA_REG_H